Dev/door section
MaSzyna-Reloaded/MaSzyna-API-wrapper pull request #14
Opened 2024-09-06 09:41 UTC by JezSonic

2024-09-08 19:58 UTC, marcinnformula requested changes
Krytyczne:
1. drzwi nie zwracają swojego stanu do API (_do_fetch_state_from_mover jest puste), dlatego nie zrobisz panela w demo app
2. brak enumów w paru miejscach
3. szamynienie ze splitowaniem stringów przeniesione do nas - zrobić dedykowane propsy

Mile widziane:
1. rozszerzenie demo app o panel ze stanem drzwi

doców nie sprawdzam, bo diffy za duże przez tabsy. Ale jeśli można, to ustawmy settingsy dla edytorów vim/vscode, żeby one w xml-ach stosowały tabsy (żeby przy uzupełnianiu doców edytory nie nam zamieniały tabów na spacje)

2024-09-08 19:58 UTC, marcinnformula commented on doc_classes/GenericTrainPart.xml
> +		<method name="get_train_controller_node">
wcięcia się zmasakrowały we wszystkich docach :D

2024-09-08 19:58 UTC, marcinnformula commented on src/core/TrainController.hpp
> +            TMoverParameters *mover{};
?

2024-09-08 19:58 UTC, marcinnformula commented on src/core/utils.cpp
> +
zbedne linebreaks?

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.cpp
> +        ClassDB::bind_method(D_METHOD("set_door_stay_open", "open_control"), &TrainDoor::set_door_stay_open);
Co to jest? Może da się czytelniej nazwać niż w moverze?

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.cpp
> +                        "Passenger,AutomaticCtrl,DriverCtrl,Conductor,Mixed"), "set_door_close_method", "get_door_close_method");
Może zastosować tutaj DRY i nie powielać? Ta sama lista jest przy open/method

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.cpp
> +        const auto permit_presets = door_permit_list.split("|");
A nie lepiej zrobić TypedArray[String]? Może nie róbmy we wrapperze Szamynienia.

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.hpp
> +            String door_permit_list = "0|0|0";
TypedArray[String] ?

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.hpp
> +             * 1 - continuous light when any door is open or any step is extended; flashing only when permission is
Może zróbmy jakieś enumy do tych rzeczy. Nie będzie zgadywanki.

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.hpp
> +             * 1 - Rot
Lepszy byłby enum

2024-09-08 19:58 UTC, marcinnformula commented on doc_classes/TrainDoor.xml
> +			1 - continuous light when any door is open or any step is extended; flashing only when permission is granted
enum

2024-09-08 19:58 UTC, marcinnformula commented on src/doors/TrainDoor.cpp
> +    void TrainDoor::_do_fetch_state_from_mover(TMoverParameters *mover, Dictionary &state) {}
Drzwi nie mają stanu?

2024-09-11 20:46 UTC, marcinn commented
![image](https://github.com/user-attachments/assets/72bb5ebf-3337-41c8-acd9-4100b01b1474)

Do tego celu nałożyłbym tego patcha (`patch -p1`):
```
diff --git a/src/doors/TrainDoor.cpp b/src/doors/TrainDoor.cpp
index 6d5f0f5..1308d60 100644
--- a/src/doors/TrainDoor.cpp
+++ b/src/doors/TrainDoor.cpp
@@ -3,7 +3,8 @@
 namespace godot {
     TrainDoor::TrainDoor() = default;
 
-    void TrainDoor::_bind_methods() {;
+    void TrainDoor::_bind_methods() {
+        ;
         ClassDB::bind_method(D_METHOD("set_door_open_time", "open_time"), &TrainDoor::set_door_open_time);
         ClassDB::bind_method(D_METHOD("get_door_open_time"), &TrainDoor::get_door_open_time);
         ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "open_time"), "set_door_open_time", "get_door_open_time");
@@ -18,12 +19,18 @@ namespace godot {
         ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "max_shift"), "set_door_max_shift", "get_door_max_shift");
         ClassDB::bind_method(D_METHOD("set_door_open_method", "door_open_method"), &TrainDoor::set_door_open_method);
         ClassDB::bind_method(D_METHOD("get_door_open_method"), &TrainDoor::get_door_open_method);
-        ADD_PROPERTY(PropertyInfo(Variant::INT, "open/method", PROPERTY_HINT_ENUM,
-                        "Passenger,AutomaticCtrl,DriverCtrl,Conductor,Mixed"), "set_door_open_method", "get_door_open_method");
+        ADD_PROPERTY(
+                PropertyInfo(
+                        Variant::INT, "open/method", PROPERTY_HINT_ENUM,
+                        "Passenger,AutomaticCtrl,DriverCtrl,Conductor,Mixed"),
+                "set_door_open_method", "get_door_open_method");
         ClassDB::bind_method(D_METHOD("set_door_close_method", "door_close_method"), &TrainDoor::set_door_close_method);
         ClassDB::bind_method(D_METHOD("get_door_close_method"), &TrainDoor::get_door_close_method);
-        ADD_PROPERTY(PropertyInfo(Variant::INT, "close/method", PROPERTY_HINT_ENUM,
-                        "Passenger,AutomaticCtrl,DriverCtrl,Conductor,Mixed"), "set_door_close_method", "get_door_close_method");
+        ADD_PROPERTY(
+                PropertyInfo(
+                        Variant::INT, "close/method", PROPERTY_HINT_ENUM,
+                        "Passenger,AutomaticCtrl,DriverCtrl,Conductor,Mixed"),
+                "set_door_close_method", "get_door_close_method");
         ClassDB::bind_method(D_METHOD("set_door_voltage", "door_voltage"), &TrainDoor::set_door_voltage);
         ClassDB::bind_method(D_METHOD("get_door_voltage"), &TrainDoor::get_door_voltage);
         ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "voltage"), "set_door_voltage", "get_door_voltage");
@@ -61,7 +68,9 @@ namespace godot {
                 PropertyInfo(Variant::FLOAT, "max_shift_plug"), "set_door_max_shift_plug", "get_door_max_shift_plug");
         ClassDB::bind_method(D_METHOD("set_door_permit_list", "door_permit_list"), &TrainDoor::set_door_permit_list);
         ClassDB::bind_method(D_METHOD("get_door_permit_list"), &TrainDoor::get_door_permit_list);
-        ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "permit/list", PROPERTY_HINT_ARRAY_TYPE), "set_door_permit_list", "get_door_permit_list");
+        ADD_PROPERTY(
+                PropertyInfo(Variant::ARRAY, "permit/list", PROPERTY_HINT_ARRAY_TYPE), "set_door_permit_list",
+                "get_door_permit_list");
         ClassDB::bind_method(
                 D_METHOD("set_door_permit_list_default", "door_permit_list_default"),
                 &TrainDoor::set_door_permit_list_default);
@@ -76,15 +85,18 @@ namespace godot {
                 PropertyInfo(Variant::BOOL, "auto_close/remote"), "set_door_auto_close_remote",
                 "get_door_auto_close_remote");
         ClassDB::bind_method(
-                D_METHOD("set_door_auto_close_velocity", "auto_close_velocity"), &TrainDoor::set_door_auto_close_velocity);
+                D_METHOD("set_door_auto_close_velocity", "auto_close_velocity"),
+                &TrainDoor::set_door_auto_close_velocity);
         ClassDB::bind_method(D_METHOD("get_door_auto_close_velocity"), &TrainDoor::get_door_auto_close_velocity);
         ADD_PROPERTY(
-        PropertyInfo(Variant::FLOAT, "auto_close/velocity"), "set_door_auto_close_velocity", "get_door_auto_close_velocity");
+                PropertyInfo(Variant::FLOAT, "auto_close/velocity"), "set_door_auto_close_velocity",
+                "get_door_auto_close_velocity");
         ClassDB::bind_method(
                 D_METHOD("set_door_auto_close_enabled", "auto_close_enabled"), &TrainDoor::set_door_auto_close_enabled);
         ClassDB::bind_method(D_METHOD("get_door_auto_close_enabled"), &TrainDoor::get_door_auto_close_enabled);
         ADD_PROPERTY(
-                PropertyInfo(Variant::BOOL, "auto_close/enabled"), "set_door_auto_close_enabled", "get_door_auto_close_enabled");
+                PropertyInfo(Variant::BOOL, "auto_close/enabled"), "set_door_auto_close_enabled",
+                "get_door_auto_close_enabled");
         //@TODO: Add bool to enable the velocity instead of setting it to -1 in the inspector
         ClassDB::bind_method(
                 D_METHOD("set_door_platform_max_speed", "platform_max_speed"), &TrainDoor::set_door_platform_max_speed);
@@ -92,9 +104,12 @@ namespace godot {
         ADD_PROPERTY(
                 PropertyInfo(Variant::FLOAT, "platform/max_speed"), "set_door_platform_max_speed",
                 "get_door_platform_max_speed");
-        ClassDB::bind_method(D_METHOD("set_platform_open_method", "platform_open_method"), &TrainDoor::set_platform_open_method);
+        ClassDB::bind_method(
+                D_METHOD("set_platform_open_method", "platform_open_method"), &TrainDoor::set_platform_open_method);
         ClassDB::bind_method(D_METHOD("get_platform_open_method"), &TrainDoor::get_platform_open_method);
-        ADD_PROPERTY(PropertyInfo(Variant::INT, "platform/open_method", PROPERTY_HINT_ENUM, "Shift,Rot"), "set_platform_open_method", "get_platform_open_method");
+        ADD_PROPERTY(
+                PropertyInfo(Variant::INT, "platform/open_method", PROPERTY_HINT_ENUM, "Shift,Rot"),
+                "set_platform_open_method", "get_platform_open_method");
         ClassDB::bind_method(
                 D_METHOD("set_door_platform_max_shift", "platform_max_shift"), &TrainDoor::set_door_platform_max_shift);
         ClassDB::bind_method(D_METHOD("get_door_platform_max_shift"), &TrainDoor::get_door_platform_max_shift);
@@ -129,7 +144,11 @@ namespace godot {
         state["door/auto_duration"] = mover->Doors.auto_duration;
         state["door/auto_include_remote"] = mover->Doors.auto_include_remote;
         state["door/permit_needed"] = mover->Doors.permit_needed;
-        state["door/permit_presets"] = String(std::string(mover->Doors.permit_presets.begin(), mover->Doors.permit_presets.end()).c_str());
+        Array permit_presets;
+        for (int element: mover->Doors.permit_presets) {
+            permit_presets.append(element);
+        }
+        state["door/permit_presets"] = permit_presets;
         state["door/open_speed"] = mover->Doors.open_rate;
         state["door/open_delay"] = mover->Doors.open_delay;
         state["door/open_time"] = mover->Doors.auto_velocity;
@@ -185,24 +204,21 @@ namespace godot {
         mover->Doors.range = door_max_shift;
         mover->Doors.range_out = door_max_shift_plug;
         const std::map<std::string, int>::iterator lookup = DoorTypes.find(IntToDoorTypes[door_open_method]);
-        mover->Doors.type =
-            lookup != DoorTypes.end() ?
-                lookup->second :
-                2;
+        mover->Doors.type = lookup != DoorTypes.end() ? lookup->second : 2;
         mover->Doors.has_warning = door_closure_warning;
         mover->Doors.has_autowarning = auto_door_closure_warning;
         mover->Doors.has_lock = door_blocked;
 
-        bool const remote_door_control {
-                mover->Doors.open_control == control_t::driver ||
-                mover->Do [...]

2024-09-12 11:00 UTC, marcinn commented on src/core/utils.cpp
> +    std::vector<std::string> Utils::split(const std::string& s, const std::string& delimiter) {
już nieużywany, nie zostawiałbym zbędnego kodu do utrzymania

2024-09-12 11:02 UTC, marcinn commented on src/doors/TrainDoor.hpp
> +            enum permit_lights {
Trzymałbym się konwencji (może nie do końca ustalonej, co powinniśmy zrobić)

`PermitLights { ContinuousLight, FlashingOnPermissionWithStep, .... itd }`

2024-09-12 11:07 UTC, marcinn commented on src/doors/TrainDoor.hpp
> +             * Flashing of the light indicating permission to open the door on the side:
skoro masz enumy, to ten comment nie jest do konca adekwatny

2024-10-05 19:59 UTC, marcinn commented on src/doors/TrainDoor.cpp
> +    void TrainDoor::_do_fetch_state_from_mover(TMoverParameters *mover, Dictionary &state) {
Hm... większość tych properties to nie jest stan, tylko konfiguracja. Konfiguracja jest dostępna w properties nodes. Np. `needs_permit` jest w property node, który jest aplikowany do konfiguracji movera w `_do_update_mover()`. A nawet jeśli miałoby to wracać w `state`, to nazwy są lekko niespójne (`needs_permit` vs `pemit_needed`).

Stanem bieżącym systemu drzwi są parametry "runtime", czyli np. czy są otwarte czy zamknięte. Albo jak bardzo otwarte/zamknięte (i to pewnie z podziałem na lewe i prawe).  Być może będzie to też `is_opening` oraz `is_closing`, czyli stan w którym drzwi aktualnie są otwierane/zamykane. Zaglądając w Mover widzę jeszcze (do sprawdzenia): door.position, door.step_position (step_unfolding/step_folding - może to coś ciekawego).

![image](https://github.com/user-attachments/assets/9feaa85e-4865-42a8-b092-3592e4265de3)

2024-10-05 20:03 UTC, marcinn commented on src/doors/TrainDoor.cpp
> +            if (param_side >= 2 || param_side <= 0) {
Nadal widziałbym tu enumy, operowanie na int-ach jest error prone.

2024-10-05 20:06 UTC, marcinn commented on src/doors/TrainDoor.cpp
> +            if (param_state >= 2 || param_state <= 0) {
j.w.

2024-10-05 20:12 UTC, marcinn commented on src/doors/TrainDoor.cpp
> +    void TrainDoor::_do_fetch_state_from_mover(TMoverParameters *mover, Dictionary &state) {
Znalazłem jeszcze takie coś, ale nie wiem czy jest dostęp z zewnątrz: czy drzwi są aktualnie pod prądem:
![image](https://github.com/user-attachments/assets/b3703745-58a6-448d-bd14-14d972579dbb)

2024-10-05 20:20 UTC, marcinn commented on src/doors/TrainDoor.cpp
> +        if (door_voltage == -1.0) {
Nie podoba mi się ten -1 dla undefined. A -2? Albo -3? Lub -0.5? Ktoś może wstawić cokolwiek i to nie zadziała jak należy. 

IMO float dla tego propsa nie pasuje. Plik charakterystyki wyraźnie opisuje trzy możliwe wartości: `DoorVoltage=[0] (0 / 12 / 110)`. LoadFIZ na defaulcie ustawia 24 gdy jest remote door control a nie określono DoorVoltage (nie wiem czy w Maszynie 0 się do tego zalicza czy nie)

2024-10-05 20:24 UTC, marcinn commented on doc_classes/TrainDoor.xml
> +			AutomaticCtrl - doors operate automatically
Wymienione wartości nie są intami. A jeśli to są enumy, to powinien być reference do enuma. Enum będzie miał swój doc.

2024-12-09 15:51 UTC, marcinn commented
Continuation in #46

2024-12-09 15:51 UTC, closed without merging