Update documentation for android development
MaSzyna-Reloaded/MaSzyna-API-wrapper pull request #69
Opened 2024-12-17 13:04 UTC by JezSonic

2024-12-26 00:05 UTC, JezSonic commented on demo/project.godot
> +textures/vram_compression/import_etc2_astc=true
Required for mobile platforms

2024-12-26 00:44 UTC, carmel4a approved these changes
Looks ok, disclaimer - I've not tested this, but changes in .md or export_pressets cannot bite.
That compression type we may change in CI/CD process in the future if necessary (for example, if different platforms will require different compressions).

2025-01-01 23:15 UTC, marcinn requested changes
I'm getting warning: editor/export/editor_export_platform.h:179 - Code Signing: Could not find keystore, unable to export.

----

Please add suggestion to README about installing Android Studio, and which android platform(s) we're targetting, and which screen sizes. For tests I am assuming VanillaIceCream API 35 / Android 15.0.

----

I have no idea what to do with this, but compilation for `platform=android` gives these warnings:

```
Compiling shared src/core/TrainPart.cpp ...
src/maszyna/McZapkie/Oerlikon_ESt.cpp:207:15: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                        if (typeid(*Przekladniki[i]) == typeid(TRapid)) {
                                   ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:211:22: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                        } else if (typeid(*Przekladniki[i]) == typeid(TPrzeciwposlizg))
                                          ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:213:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                        else if (typeid(*Przekladniki[i]) == typeid(TPrzekED)) {
                                        ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:218:22: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                        } else if (typeid(*Przekladniki[i]) == typeid(TPrzekCiagly))
                                          ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:220:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                        else if (typeid(*Przekladniki[i]) == typeid(TPrzek_PZZ))
                                        ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:284:14: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                if (typeid(*FM) == typeid(TDisk1) || typeid(*FM) == typeid(TDisk2)) // jesli zeliwo to schodz
                           ^
src/maszyna/McZapkie/Oerlikon_ESt.cpp:284:47: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
                if (typeid(*FM) == typeid(TDisk1) || typeid(*FM) == typeid(TDisk2)) // jesli zeliwo to schodz
                                                            ^
Compiling shared src/core/TrainSystem.cpp ...
Compiling shared src/core/utils.cpp ...
Compiling shared src/doors/TrainDoors.cpp ...
Compiling shared src/engines/TrainDieselElectricEngine.cpp ...
Compiling shared src/engines/TrainDieselEngine.cpp ...
Compiling shared src/engines/TrainElectricEngine.cpp ...
Compiling shared src/engines/TrainElectricSeriesEngine.cpp ...
Compiling shared src/engines/TrainEngine.cpp ...
Compiling shared src/systems/TrainSecuritySystem.cpp ...
src/maszyna/McZapkie/Mover.cpp:1353:84: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
                        if (FuzzyLogic((AccN / g) * (1.0 + 0.1 * (Track.DamageFlag && dtrack_freerail)), TrackW / Dim.H,
                                                                                   ^  ~~~~~~~~~~~~~~~
src/maszyna/McZapkie/Mover.cpp:1353:84: note: use '&' for a bitwise operation
                        if (FuzzyLogic((AccN / g) * (1.0 + 0.1 * (Track.DamageFlag && dtrack_freerail)), TrackW / Dim.H,
                                                                                   ^~
                                                                                   &
src/maszyna/McZapkie/Mover.cpp:1353:84: note: remove constant to silence this warning
                        if (FuzzyLogic((AccN / g) * (1.0 + 0.1 * (Track.DamageFlag && dtrack_freerail)), TrackW / Dim.H,
                                                                                  ~^~~~~~~~~~~~~~~~~~
src/maszyna/McZapkie/Mover.cpp:2260:97: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                                            if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                                ^~~~~~~~
src/maszyna/McZapkie/Mover.cpp:2260:97: note: place parentheses around the '==' expression to silence this warning
                                            if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                                ^
                                                                                                  (     )
src/maszyna/McZapkie/Mover.cpp:2260:97: note: place parentheses around the & expression to evaluate it first
                                            if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                                ^
                                                                       (                           )
src/maszyna/McZapkie/hamulce.cpp:523:17: warning: add explicit braces to avoid dangling else [-Wdangling-else]
                else {
                ^
src/maszyna/McZapkie/Mover.cpp:2248:29: warning: enumeration values 'SteamEngine' and 'Main' not handled in switch [-Wswitch]
                    switch (EngineType) {
                            ^
src/maszyna/McZapkie/Mover.cpp:2409:95: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                                                                    (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                              ^~~~~~~~
src/maszyna/McZapkie/Mover.cpp:2409:95: note: place parentheses around the '==' expression to silence this warning
                                                                    (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                              ^
                                                                                                (     )
src/maszyna/McZapkie/Mover.cpp:2409:95: note: place parentheses around the & expression to evaluate it first
                                                                    (SpeedCtrlAutoTurnOffFlag & 1 == 1) &&
                                                                                              ^
                                                                     (                           )
src/maszyna/McZapkie/Mover.cpp:2397:49: warning: enumeration values 'WheelsDriven', 'SteamEngine', and 'Main' not handled in switch [-Wswitch]
                                        switch (EngineType) {
                                                ^
src/maszyna/McZapkie/Mover.cpp:2570:73: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                    if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1)) {
                                                                        ^~~~~~~~
src/maszyna/McZapkie/Mover.cpp:2570:73: note: place parentheses around the '==' expression to silence this warning
                    if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1)) {
                                                                        ^
                                                                          (     )
src/maszyna/McZapkie/Mover.cpp:2570:73: note: place parentheses around the & expression to evaluate it first
                    if ((EIMCtrlType == 0) && (SpeedCtrlAutoTurnOffFlag & 1 == 1)) {
       [...]

2025-01-02 00:02 UTC, marcinn commented
I finally signed exported apk, configured emulator and installed apk via adb (please consider adding a small howto, maybe for README_Android.md?) 

Unfortunately game is crashing:
```
01-02 00:52:54.207  5634  5634 D nativeloader: Configuring clns-7 for other apk /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64:/data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.maszynareloaded.demo
01-02 00:52:54.405  5634  5634 D nativeloader: Load /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so using ns clns-7 from class loader (caller=/data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/base.apk): ok
01-02 00:52:54.534   599   621 V WindowManager:         {WCT{RemoteToken{6bba0a4 Task{5026186 #14 type=standard A=10209:com.maszynareloaded.demo}}} m=CHANGE f=NONE p=WCT{RemoteToken{8b27d2e DefaultTaskDisplayArea@249614487}} leash=Surface(name=Task=14)/@0xaec3836 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 2400, 1080) d=0 r=0->1:-1 taskParent=-1},
01-02 00:52:55.472  5660  5660 F DEBUG   : Cmdline: com.maszynareloaded.demo
01-02 00:52:55.472  5660  5660 F DEBUG   : pid: 5634, tid: 5634, name: nareloaded.demo  >>> com.maszynareloaded.demo <<<
01-02 00:52:55.476  5660  5660 F DEBUG   :       #00 pc 00000000012d0ba0  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #01 pc 00000000012ceae8  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #02 pc 00000000012ce37c  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #03 pc 00000000031411d4  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #04 pc 00000000030544e8  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #05 pc 0000000000e2c740  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so
01-02 00:52:55.476  5660  5660 F DEBUG   :       #06 pc 0000000000e10e18  /data/app/~~UQ_H0v9pBJM2Iv6JQ9yvJQ==/com.maszynareloaded.demo-bB4jKfTwvJS-gMJI9ItVkw==/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_setup+320)
01-02 00:52:55.479   599  5663 E ActivityManager: App crashed on incremental package com.maszynareloaded.demo which is 100% loaded.
01-02 00:52:55.480   599  5663 W ActivityTaskManager:   Force finishing activity com.maszynareloaded.demo/com.godot.game.GodotApp
01-02 00:52:55.495   599  1113 I ActivityManager: Process com.maszynareloaded.demo (pid 5634) has died: fg  TOP 
```


----

I am not sure what the goal of this PR is, so I assumed a successful android build. In such case I can't confirm is this working as expected. Maybe I did something wrong with my Android SDK setup, but there is no required info in docs. Therefore, I cannot say whether the documentation is complete and whether the project is fully configured.

2025-01-02 00:24 UTC, marcinn commented
But Mover is working! :smile: :+1: 

![image](https://github.com/user-attachments/assets/01141dc5-d388-47c2-9f17-8f72a43a80c8)

2025-01-03 15:14 UTC, marcinn approved these changes
thanks!

2025-01-03 15:16 UTC, merged